repositories:
#- name: stable
#  url: https://charts.helm.sh/stable
- name: bitnami
  url: https://charts.bitnami.com/bitnami

helmDefaults:
  wait: true
  createNamespace: false

releases:
- name: mongodb
  chart: bitnami/mongodb
  values:
  - values.yaml
- name: hygieia
  chart: ./charts/hygieia
  values:
  - values.yaml