apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hygieia
  labels:
    app: hygieia
spec:
  defaultBackend:
    service:
      name: hygieia-headless
      port:
        number: {{ .Values.ui.port }}