apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hygieia
  labels:
    app: hygieia
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hygieia
            port:
              number: 80