{{ if .Values.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: hygieia
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: hygieia-0
  ports:
  - protocol: TCP
    port: {{ .Values.ui.port }}
    targetPort: {{ .Values.ui.port }}
{{ end }}