apiVersion: v1
kind: Service
metadata:
  name: hygieia-headless
  labels:
    app: hygieia
spec:
  selector:
    app: hygieia
  ports:
  - protocol: TCP
    port: {{ .Values.ui.port }}
    targetPort: {{ .Values.ui.port }}
  clusterIP: None