apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hygieia
  labels:
    app: hygieia
spec:
  replicas: 1
  serviceName: hygieia
  selector:
    matchLabels:
      app: hygieia
  template:
    metadata:
      labels:
        app: hygieia
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "api"
      containers:
      - name: 'api'
        image: hygieia-api
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: "mongodb"
      - name: 'ui'
        image: hygieia-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80