apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hygieia
  labels:
    app: hygieia
spec:
  replicas: 1
  serviceName: hygieia
  selector:
    matchLabels:
      app: hygieia
  template:
    metadata:
      labels:
        app: hygieia
    spec:
      containers:
      - name: 'api'
        image: hygieia-api
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: "mongodb"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_PASSWORD
          value: "{{ .Values.auth.password }}"
        - name: MONGODB_USERNAME
          value: "{{ .Values.auth.username }}"
        - name: MONGODB_DBNAME
          value: "{{ .Values.auth.database }}"
        - name: MONGODB_REPLICASET
          value: "false"
        - name: SERVER_PORT
          value: "{{ .Values.api.port }}"
        - name: SERVER_CONTEXT_PATH
          value: "/api"
      - name: 'ui'
        image: hygieia-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.ui.port }}
        env:
        - name: API_HOST
          value: "{{ .Values.api.host }}"
        - name: API_PORT
          value: "{{ .Values.api.port }}"
        - name: UI_HOSTNAME
          value: "{{ .Values.ui.host }}"
        - name: UI_PORT
          value: "{{ .Values.ui.port }}"